apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-cont
        image: registry.ntnx.fr/local/k8s_day3:1.0
        imagePullPolicy: Always
        env:
          - name: LAB_NUMBER
            value: "5"
          - name: MYNAMEIS
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: my-name
          - name: MYPASSWORDIS
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: my-password
        volumeMounts:
            - mountPath: /data
              name: fromconfigmap
            - mountPath: /pvdata
              name: mypvc
      volumes:
        - name: fromconfigmap
          configMap:
            name: my-configmap
            items:
              - key: my-data
                path: "MyData.txt"
        - name: mypvc
          persistentVolumeClaim:
            claimName: my-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  my-name: "Gautier LEBLANC"
  my-data: "Mon texte bidon
            fdsf"
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  my-password: TW9uU2VjcmV0Cg==
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: my-pvc
spec:
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 4Gi
