apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-cont
        image: registry.ntnx.fr/local/k8s_day3:1.0
        imagePullPolicy: Always
        env:
          - name: LAB_NUMBER
            value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80