---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
    type: webserver
spec:
  containers:
  - name: myapp
    image: registry.ntnx.fr/training/evonyee
    ports:
    - containerPort: 80
