apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
        type: webserver
    spec:
      containers:
      - name: myapp
        image: registry.ntnx.fr/training/evonyee
        ports:
          - containerPort: 80