apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-myapp
  labels:
    app: myapp
spec:
  #strategy: 
  #  type: Recreate
  replicas: 10
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
        type: webserver
    spec:
      containers:
      - name: myapp
        image: registry.ntnx.fr/training/evonyee
        ports:
          - containerPort: 80